### ISSUE TITLE
tex2Dgrad causes strange issues

### ISSUE THREAD

**Issue by bonjorno7** [SCell555/ShaderCompile#3]
When used in a loop, the loop is not unrolled, or at least there's no warning saying it is. It seems I'm allowed to go over the temp register limit when using it, which causes unexpected behavior in game. I'll provide a screenshot in a bit. To make parallax work with this ShaderCompile I ended up having to change tex2Dgrad to tex2D, and reducing the amount of layers from 20 to 10. It does build in 3 minutes instead of 30 though so that's nice.

**Comment by SCell555** [comment]
I tried to reproduce this behavior. I got files from [standalone-shadercompile](https://github.com/momentum-mod/game/commits/feature/standalone-shadercompile) branch, and tried to compile pbr_ps30 with and without changes from https://github.com/momentum-mod/game/commit/29a66aabfc10edc6cae0ccdac1b73964702db6f9. Only warning I got was with tex2D lookup about forced unroll, and build times didn't change at all (~2 min). Next I tried parallaxCorrect function with [unroll] above while loop and with tex2Dgrad and it looked normal.
![shadertest0001](https://user-images.githubusercontent.com/2620789/81184010-2bcb9600-8fb0-11ea-9c1f-b5cd12520e1d.jpg)

But I found an issue with field sizes in combo classes, it would set for example NUM_LIGHTS to 4, but variable stored -4, because it was signed int

**Comment by bonjorno7** [comment]
![Desktop Screenshot 2020 05 06 - 20 10 22 35](https://user-images.githubusercontent.com/43251584/81213071-1ec19d80-8fd6-11ea-98f7-6b2c06e97280.png)
![Desktop Screenshot 2020 05 06 - 20 10 34 50](https://user-images.githubusercontent.com/43251584/81213076-21bc8e00-8fd6-11ea-984b-4d17da66f2a8.png)
Here's what using tex2Dgrad does for me.

**Comment by bonjorno7** [comment]
Also I can't build the game because of missing inc files, which I can't generate because.. I don't know, maybe we don't have the fxc files or something.

**Comment by bonjorno7** [comment]
Could you try making a branch off of Momentum Mod's [develop](https://github.com/momentum-mod/game/tree/develop) branch (don't use another branch, they're all messy WIP stuff) and installing your ShaderCompile? That would be a massive help because I've been throwing myself at this for days and failing.

**Comment by SCell555** [comment]
I added ShaderCompile to [new](https://github.com/SCell555/game/tree/new-shadercompile) branch, shader dll is compilable, didn't try to compile any shaders. I renamed all shader files to lowercase, they were creating a mess. Also I removed all dx8 files.
